<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class CourseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $mentorId = User::query()->where('email', 'mentor@elearning.local')->value('id');

        $courses = [
            [
                'title' => 'Project Management Essentials',
                'slug' => 'project-management-essentials',
                'description' => 'Belajar membuat rencana kerja, timeline, dan tracking progress tim.',
                'level' => 'Pemula',
                'duration_weeks' => 4,
                'category' => 'Productivity',
                'price_amount' => 349000,
                'currency' => 'IDR',
                'trailer_video_url' => 'https://www.youtube.com/embed/2ReR1YJrNOM',
                'tools' => ['Notion', 'Trello', 'Google Sheets'],
            ],
            [
                'title' => 'Komunikasi Profesional',
                'slug' => 'komunikasi-profesional',
                'description' => 'Meningkatkan keterampilan komunikasi lintas tim dan lintas divisi.',
                'level' => 'Menengah',
                'duration_weeks' => 3,
                'category' => 'Soft Skills',
                'price_amount' => 299000,
                'currency' => 'IDR',
                'trailer_video_url' => 'https://www.youtube.com/embed/UNP03fDSj1U',
                'tools' => ['Zoom', 'Miro', 'Google Docs'],
            ],
            [
                'title' => 'Data Analysis Fundamentals',
                'slug' => 'data-analysis-fundamentals',
                'description' => 'Pahami dasar analisis data untuk pengambilan keputusan berbasis metrik.',
                'level' => 'Pemula',
                'duration_weeks' => 6,
                'category' => 'Analytics',
                'price_amount' => 459000,
                'currency' => 'IDR',
                'trailer_video_url' => 'https://www.youtube.com/embed/ua-CiDNNj30',
                'tools' => ['Google Colab', 'Looker Studio', 'Spreadsheet'],
            ],
            [
                'title' => 'Fullstack Web: Nuxt 4 & Laravel 13 API Enterprise',
                'slug' => 'fullstack-web-nuxt-4-laravel-13-api-enterprise',
                'description' => 'Membangun aplikasi modern dari frontend SSR hingga backend API production-ready.',
                'level' => 'Menengah',
                'duration_weeks' => 10,
                'category' => 'Web Development',
                'price_amount' => 499000,
                'currency' => 'IDR',
                'trailer_video_url' => 'https://www.youtube.com/embed/4vN0x7S7RJs',
                'tools' => ['Nuxt 4', 'Laravel 13', 'PostgreSQL', 'Redis'],
            ],
            [
                'title' => 'Dasar Pemrograman Web: HTML, CSS & JS',
                'slug' => 'dasar-pemrograman-web-html-css-js',
                'description' => 'Fondasi wajib untuk pemula mulai dari struktur halaman hingga interaksi dinamis.',
                'level' => 'Pemula',
                'duration_weeks' => 6,
                'category' => 'Web Development',
                'price_amount' => 0,
                'currency' => 'IDR',
                'trailer_video_url' => 'https://www.youtube.com/embed/mU6anWqZJcc',
                'tools' => ['VS Code', 'Chrome DevTools'],
            ],
            [
                'title' => 'Modern JavaScript Masterclass (ES6+)',
                'slug' => 'modern-javascript-masterclass-es6-plus',
                'description' => 'Kuasai syntax modern JavaScript, async flow, dan pola reusable untuk aplikasi besar.',
                'level' => 'Pemula',
                'duration_weeks' => 7,
                'category' => 'Web Development',
                'price_amount' => 299000,
                'currency' => 'IDR',
                'trailer_video_url' => 'https://www.youtube.com/embed/PkZNo7MFNFg',
                'tools' => ['JavaScript', 'Vite', 'ESLint'],
            ],
            [
                'title' => 'Mastering PostgreSQL 17 & Redis 7 Caching',
                'slug' => 'mastering-postgresql-17-redis-7-caching',
                'description' => 'Optimasi performa query, indexing strategy, dan cache layer untuk API skala tinggi.',
                'level' => 'Lanjutan',
                'duration_weeks' => 8,
                'category' => 'Backend & Database',
                'price_amount' => 399000,
                'currency' => 'IDR',
                'trailer_video_url' => 'https://www.youtube.com/embed/SpfIwlAYaKk',
                'tools' => ['PostgreSQL 17', 'Redis 7', 'pgAdmin'],
            ],
            [
                'title' => 'Laravel Sanctum Auth & REST API Security',
                'slug' => 'laravel-sanctum-auth-rest-api-security',
                'description' => 'Bangun autentikasi aman berbasis token, policy, dan proteksi endpoint API.',
                'level' => 'Menengah',
                'duration_weeks' => 6,
                'category' => 'Backend & Database',
                'price_amount' => 450000,
                'currency' => 'IDR',
                'trailer_video_url' => 'https://www.youtube.com/embed/1nVu-6YwRRM',
                'tools' => ['Laravel Sanctum', 'Postman', 'MySQL'],
            ],
            [
                'title' => 'Golang Microservices & gRPC Architecture',
                'slug' => 'golang-microservices-grpc-architecture',
                'description' => 'Pisahkan monolith menjadi service modular dengan gRPC, event, dan observability.',
                'level' => 'Lanjutan',
                'duration_weeks' => 9,
                'category' => 'Backend & Database',
                'price_amount' => 650000,
                'currency' => 'IDR',
                'trailer_video_url' => 'https://www.youtube.com/embed/yyUHQIec83I',
                'tools' => ['Go', 'gRPC', 'Prometheus', 'Grafana'],
            ],
            [
                'title' => 'Docker Compose & Nginx Reverse Proxy Setup',
                'slug' => 'docker-compose-nginx-reverse-proxy-setup',
                'description' => 'Deploy multi-service app dengan praktik containerization dan reverse proxy aman.',
                'level' => 'Menengah',
                'duration_weeks' => 5,
                'category' => 'DevOps & Cloud',
                'price_amount' => 549000,
                'currency' => 'IDR',
                'trailer_video_url' => 'https://www.youtube.com/embed/6Yis0NfNfP8',
                'tools' => ['Docker Compose', 'Nginx', 'Linux CLI'],
            ],
            [
                'title' => 'Kubernetes (K8s) & CI/CD Pipelines Mastery',
                'slug' => 'kubernetes-k8s-cicd-pipelines-mastery',
                'description' => 'Automasi deployment modern dengan pipeline, container registry, dan monitoring.',
                'level' => 'Lanjutan',
                'duration_weeks' => 9,
                'category' => 'DevOps & Cloud',
                'price_amount' => 750000,
                'currency' => 'IDR',
                'trailer_video_url' => 'https://www.youtube.com/embed/X48VuDVv0do',
                'tools' => ['Kubernetes', 'GitHub Actions', 'Helm'],
            ],
            [
                'title' => 'UI/UX Design System untuk Aplikasi SaaS',
                'slug' => 'ui-ux-design-system-untuk-aplikasi-saas',
                'description' => 'Rancang komponen konsisten, token, dan guideline agar desain mudah di-scale.',
                'level' => 'Pemula',
                'duration_weeks' => 7,
                'category' => 'UI/UX Design',
                'price_amount' => 450000,
                'currency' => 'IDR',
                'trailer_video_url' => 'https://www.youtube.com/embed/8f7k6xS6A1s',
                'tools' => ['Figma', 'Design Tokens', 'Storybook'],
            ],
            [
                'title' => 'Figma to Code: UI/UX Advanced Prototyping',
                'slug' => 'figma-to-code-ui-ux-advanced-prototyping',
                'description' => 'Ubah prototype menjadi handoff siap implementasi dengan dokumentasi rapi.',
                'level' => 'Menengah',
                'duration_weeks' => 6,
                'category' => 'UI/UX Design',
                'price_amount' => 390000,
                'currency' => 'IDR',
                'trailer_video_url' => 'https://www.youtube.com/embed/wQAH66tQk6U',
                'tools' => ['Figma', 'Autolayout', 'Prototype Flows'],
            ],
            [
                'title' => 'Belajar Fundamental Python Data Science',
                'slug' => 'belajar-fundamental-python-data-science',
                'description' => 'Mulai dari Python dasar, data wrangling, hingga visualisasi untuk insight bisnis.',
                'level' => 'Pemula',
                'duration_weeks' => 7,
                'category' => 'Data Science',
                'price_amount' => 350000,
                'currency' => 'IDR',
                'trailer_video_url' => 'https://www.youtube.com/embed/rfscVS0vtbw',
                'tools' => ['Python', 'Pandas', 'Matplotlib'],
            ],
            [
                'title' => 'Machine Learning with Python & Scikit-Learn',
                'slug' => 'machine-learning-with-python-scikit-learn',
                'description' => 'Terapkan model klasifikasi dan regresi ke studi kasus nyata dengan evaluasi tepat.',
                'level' => 'Menengah',
                'duration_weeks' => 8,
                'category' => 'Data Science',
                'price_amount' => 550000,
                'currency' => 'IDR',
                'trailer_video_url' => 'https://www.youtube.com/embed/7eh4d6sabA0',
                'tools' => ['Scikit-Learn', 'Jupyter', 'NumPy'],
            ],
            [
                'title' => 'Mastering React Native 2026',
                'slug' => 'mastering-react-native-2026',
                'description' => 'Bangun aplikasi lintas platform dengan performa tinggi dan arsitektur bersih.',
                'level' => 'Menengah',
                'duration_weeks' => 8,
                'category' => 'Mobile App',
                'price_amount' => 599000,
                'currency' => 'IDR',
                'trailer_video_url' => 'https://www.youtube.com/embed/0-S5a0eXPoc',
                'tools' => ['React Native', 'Expo', 'TypeScript'],
            ],
            [
                'title' => 'Flutter State Management: Bloc & Riverpod',
                'slug' => 'flutter-state-management-bloc-riverpod',
                'description' => 'Kelola state kompleks aplikasi mobile secara stabil dan terukur.',
                'level' => 'Lanjutan',
                'duration_weeks' => 7,
                'category' => 'Mobile App',
                'price_amount' => 500000,
                'currency' => 'IDR',
                'trailer_video_url' => 'https://www.youtube.com/embed/fq4N0hgOWzU',
                'tools' => ['Flutter', 'Bloc', 'Riverpod'],
            ],
            [
                'title' => 'Cyber Security Fundamental untuk Web Engineer',
                'slug' => 'cyber-security-fundamental-untuk-web-engineer',
                'description' => 'Pelajari OWASP Top 10, hardening server, dan incident response dasar.',
                'level' => 'Menengah',
                'duration_weeks' => 6,
                'category' => 'Cyber Security',
                'price_amount' => 520000,
                'currency' => 'IDR',
                'trailer_video_url' => 'https://www.youtube.com/embed/3Kq1MIfTWCE',
                'tools' => ['OWASP ZAP', 'Burp Suite', 'Linux'],
            ],
        ];

        foreach ($courses as $course) {
            Course::query()->updateOrCreate(
                ['slug' => $course['slug']],
                [
                    ...$course,
                    'mentor_user_id' => $mentorId,
                    'is_published' => true,
                    'published_at' => Carbon::now(),
                ]
            );
        }
    }
}
